name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    if: github.event.repository.fork == false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby

    - name: Release
      run: rake -f -r bundler/gem_tasks release
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
